# HEADER
PARAM_FILE_NAME="FLU-2x75-secondary"
PARAM_FILE_AUTHOR="K. Lacek; B. Rambo-Martin"
PARAM_FILE_VERSION="1.0"
PARAM_FILE_DATE="2023-10-27"

# CONSENSUS REFINEMENT & READ SELECTION
MIN_LEN=70				# minimum read length for QUALITY reads

# VARIANT CALLING HEURISTICS & STATS
ALIGN_PROG="SAM"       # rough alignment with SAM

# SECONDARY ASSEMBLY
RESIDUAL_ASSEMBLY_FACTOR=400
MIN_RP_RESIDUAL=150
MIN_RC_RESIDUAL=150
DO_SECONDARY=1