# HEADER
PARAM_FILE_NAME="CoV S-gene"
PARAM_FILE_AUTHOR="K. Lacek"
PARAM_FILE_VERSION="1.0"
PARAM_FILE_DATE="2024-10"

MIN_CONS_SUPPORT=30
ASSEM_REF=1

PADDED_CONSENSUS=1
CUSTOM_REF_FILE="SARS-CoV-2_spike.fasta"   # custom ref file
REF_SET=$(dirname $REF_SET)/$CUSTOM_REF_FILE

