version: "3.9"

x-spyne-git-version: 
  &spyne-git-version 
  https://github.com/rchau88/spyne-RC.git#single_spyne_container

x-data-volumes:
  &data-volume
  type: bind
  source: /home/snu3/Github/FLU_SC2_SEQUENCING
  target: /data

services:
  spyne: 
    container_name: spyne
    image: spyne:latest
    build:
      context: *spyne-git-version
      args:
        - irma_image=cdcgov/irma:v1.1.2
        - dais_image=cdcgov/dais-ribosome:v1.3.2
    restart: always
    volumes:
      - *data-volume
    command: tail -f /dev/null

