version: "3.9"

x-spyne-version: 
  &spyne-version
  cdcgov/spyne-dev:latest

x-data-volumes:
  &data-volume
  type: bind
  source: /home/snu3/Github/FLU_SC2_SEQUENCING
  target: /data

services:
  spyne: 
    container_name: spyne
    image: *spyne-version
    restart: always
    volumes:
      - *data-volume
    command: tail -f /dev/null

