version: "3.9"

x-spyne-git-version: 
  &spyne-git-version 
 https://github.com/CDCgov/spyne.git#single_spyne_container

x-data-volumes:
  &data-volume
  type: bind
  source: /home/snu3/Github/FLU_SC2_SEQUENCING_NEW
  target: /data

x-spyne-code:
  &spyne-code
  type: bind
  source: /home/snu3/Github/spyne
  target: /spyne  

services:
  spyne-new: 
    container_name: spyne-new
    image: spyne:latest
    build:
      context: *spyne-git-version
      args:
        - irma_image=cdcgov/irma:v1.1.2
        - dais_image=cdcgov/dais-ribosome:v1.3.2
    restart: always
    volumes:
      - *data-volume
      - *spyne-code
    command: tail -f /dev/null

