channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - biopython>=1.78
  - bbmap
  - pandas
  - python
  - readline
  - snakefmt
  - snakemake
  - blat
  - minimap2
  - parallel
  - pigz
  - samtools
  - fasttree
  - muscle
  - shogun
